#!/bin/bash

#########################################################
#
# Platform: NCI Gadi HPC
# Description: Performs adapter and polyA tail trimming.
# Runs bbduk_trim_paired.sh in parallel if bbduk_trim_paired.inputs exists.
# Runs bbduk_trim_single.sh in parallel if bbduk_trim_single.inputs exists.
# Will automatically look for either input file.
# Usage: Adjust <project> and compute resource requests following the guide
# below, then qsub bbduk_trim_run_parallel.pbs
# Job resource requirements:
# Per task requirements:
# 1 task requires 1 CPU, 16GB mem
# Walltime depends on sequencing depth
# Author: Tracy Chew
# tracy.chew@sydney.edu.au
# Date last modified: 27/08/2020
#
# If you use this script towards a publication, please acknowledge the
# Sydney Informatics Hub (or co-authorship, where appropriate).
#
# Suggested acknowledgement:
# The authors acknowledge the scientific and technical assistance
# <or e.g. bioinformatics assistance of <PERSON>> of Sydney Informatics
# Hub and resources and services from the National Computational
# Infrastructure (NCI), which is supported by the Australian Government
# with access facilitated by the University of Sydney.
#
#########################################################

# Run bbduk adapter and polyA tail trimming
# 1 task = 1 single or 1 pair of fastq files

#PBS -P er01
#PBS -N bbduktrim
#PBS -l walltime=03:00:00,ncpus=24,mem=90GB,wd
#PBS -q normal
#PBS -W umask=022
#PBS -l storage=scratch/er01+scratch/public
#PBS -o ./Logs/bbduktrim_100_3.o
#PBS -e ./Logs/bbduktrim_100_3.e

module load openmpi/4.0.2
module load nci-parallel/1.0.0
module load bbtools/37.98

set -e

mkdir -p ./Logs

# M = Number of processes per node
# NCPUs = CPUs per task
M=''
if (( ${PBS_NCPUS}>= 48 )); then
	M=48
else
	M=${PBS_NCPUS}
fi

NCPUS=1

INPUTS=./Inputs
paired=${INPUTS}/bbduk_trim_paired.inputs
single=${INPUTS}/bbduk_trim_single.inputs

echo "$(date): BBduk is trimming adapters and polyA tails."

if [ -s ${paired} ]
then
	echo "$(date): Found inputs file for paired data"
	SCRIPT=./bbduk_trim_paired.sh
	sed "s|^|${SCRIPT} |" ${paired} > ${PBS_JOBFS}/input-file-paired
	mpirun --np ${M} \
		--map-by core:pe=${NCPUS} \
		--report-bindings \
		nci-parallel \
		--verbose \
		--input-file ${PBS_JOBFS}/input-file-paired
fi

if [ -s ${single} ]
then
	echo "$(date): Found inputs file for single data"
	SCRIPT=./bbduk_trim_single.sh
	sed "s|^|${SCRIPT} |" ${single} > ${PBS_JOBFS}/input-file-single
	mpirun --np ${M} \
		--map-by core:pe=${NCPUS} \
		--report-bindings \
		nci-parallel \
		--verbose \
		--input-file ${PBS_JOBFS}/input-file-single
fi
