#!/bin/bash

# align RNA seq fastq files using STAR
# 24 CPUs, 96Gb memory required per human/mouse sample
# can map paired and single reads in a single job
# Should scale to the number of reads in FASTQ file

#PBS -P er01
#PBS -N samtools_merge
#PBS -l walltime=05:00:00,ncpus=48,mem=192GB,wd
#PBS -q normal
#PBS -W umask=022
#PBS -l storage=scratch/er01
#PBS -o ./Logs/samtools_merge.o
#PBS -e ./Logs/samtools_merge.e

module load openmpi/4.0.2
module load nci-parallel/1.0.0
module load samtools/1.10

set -e

# NCPUs = CPUs per task
NCPUS=2

SCRIPT=./samtools_merge.sh
INPUTS=./Inputs/samtools_merge.inputs


echo "$(date): Merge multiplexed samples with SAMtools merge."

CPN=48 #CPUs per node
M=$(( CPN / NCPUS )) #tasks per node

sed "s|^|${SCRIPT} |" ${INPUTS} > ${PBS_JOBFS}/input-file

mpirun --np $((M * PBS_NCPUS / 48)) \
        --map-by node:PE=${NCPUS} \
        nci-parallel \
        --verbose \
        --input-file ${PBS_JOBFS}/input-file
