#!/bin/bash

#########################################################
#
# Platform: NCI Gadi HPC
# Description: Runs bam_stat.sh in parallel. bam_stat.sh uses
# RSeQC's bam_stat.py to collect a summary of stats on a BAM file.
# See http://rseqc.sourceforge.net/
# Stats can be used to determine the strandedness of the 
# sequencing library 
# Usage: Adjust <project> and compute resource requests following the guide
# below, then qsub bam_stat_run_parallel.pbs
# Job resource requirements:
# Per task requirements:
# 1 task requires 1 CPU, 4GB mem
# Author: Tracy Chew
# tracy.chew@sydney.edu.au
# Date last modified: 17/08/2020
#
# If you use this script towards a publication, please acknowledge the
# Sydney Informatics Hub (or co-authorship, where appropriate).
#
# Suggested acknowledgement:
# The authors acknowledge the scientific and technical assistance
# <or e.g. bioinformatics assistance of <PERSON>> of Sydney Informatics
# Hub and resources and services from the National Computational
# Infrastructure (NCI), which is supported by the Australian Government
# with access facilitated by the University of Sydney.
#
#########################################################

#PBS -P er01
#PBS -N bam_stat
#PBS -l walltime=02:00:00,ncpus=48,mem=192GB,wd
#PBS -q express
#PBS -W umask=022
#PBS -l storage=scratch/er01
#PBS -o ./Logs/bam_stat.o
#PBS -e ./Logs/bam_stat.e

module load openmpi/4.0.2
module load nci-parallel/1.0.0
module load python3/3.8.5
export PYTHONPATH=$HOME/.local/lib/python3.8/site-packages

# After module load python3/3.8.5, install RSeQC
# pip3 install RSeQC

set -e

# NCPUs = CPUs per task
NCPUS=1

SCRIPT=./bam_stat.sh
INPUTS=./Inputs/bam_stat.inputs


echo "$(date): Summarize alignment metrics from BAM file using RSeQC's bam_stat.py"

CPN=48 #CPUs per node
M=$(( CPN / NCPUS )) #tasks per node

sed "s|^|${SCRIPT} |" ${INPUTS} > ${PBS_JOBFS}/input-file

mpirun --np $((M * PBS_NCPUS / 48)) \
        --map-by node:PE=${NCPUS} \
        nci-parallel \
        --verbose \
        --input-file ${PBS_JOBFS}/input-file
