#!/bin/bash

#set -e

#########################################################
#
# Platform: NCI Gadi HPC
#
# Author: Tracy Chew
# tracy.chew@sydney.edu.au
#
# If you use this script towards a publication, please acknowledge the
# Sydney Informatics Hub (or co-authorship, where appropriate).
#
# Suggested acknowledgement:
# The authors acknowledge the scientific and technical assistance
# <or e.g. bioinformatics assistance of <PERSON>> of Sydney Informatics
# Hub and resources and services from the National Computational
# Infrastructure (NCI), which is supported by the Australian Government
# with access facilitated by the University of Sydney.
#
#########################################################

# Quite variable depending on BAM size
# Future - run each BAM as an independant job
# Could also try order inputs by BAM size (descending)

#PBS -P er01
#PBS -N htseq-count
#PBS -l walltime=6:00:00,ncpus=12,mem=190GB,wd
#PBS -q normal
#PBS -W umask=022
#PBS -l storage=scratch/er01
#PBS -o ./Logs/htseq-count.o
#PBS -e ./Logs/htseq-count.e

module purge
module load openmpi/4.0.2
module load nci-parallel/1.0.0a
#module load python3/3.8.5
#module load python3/3.11.0

#export PYTHONPATH=$HOME/.local/lib/python3.8/site-packages
# Nandan

#Based on inputs from NCI (Javed)
#module purge
#module load python3/3.11.0
#pip3 install htseq


#>pip3 install htseq
#Defaulting to user installation because normal site-packages is not writeable

#Requirement already satisfied: htseq in /home/561/npd561/.local/lib/python3.11/site-packages (2.0.2)

#Requirement already satisfied: numpy in /apps/python3/3.11.0/lib/python3.11/site-packages (from htseq) (1.23.4)
#Requirement already satisfied: pysam in /home/561/npd561/.local/lib/python3.11/site-packages (from htseq) (0.21.0)
#Requirement already satisfied: cython in /apps/python3/3.11.0/lib/python3.11/site-packages (from pysam->htseq) (0.29.32)

#### ERRORS with 3.11 (conflict with 3.8.5) So reveretd to 3.8.5

#module purge
#module load python3/3.8.5
#pip3 install htseq

#pip3 install htseq
# Defaulting to user installation because normal site-packages is not writeable
# Requirement already satisfied: htseq in /home/561/npd561/.local/lib/python3.8/site-packages (2.0.2)
# Requirement already satisfied: numpy in /apps/python3/3.8.5/lib/python3.8/site-packages/numpy-1.19.1-py3.8-linux-x86_64.egg (from htseq) (1.19.1)
# Requirement already satisfied: pysam in /home/561/npd561/.local/lib/python3.8/site-packages (from htseq) (0.21.0)
# Requirement already satisfied: cython in /apps/python3/3.8.5/lib/python3.8/site-packages (from pysam->htseq) (0.29.21)




#export PYTHONPATH=/home/561/npd561/.local/lib/python3.11/site-packages
#export PYTHONPATH=/apps/python3/3.11.0/bin/python3.11/site-packages

#export PYTHONPATH=/home/561/npd561/.local/lib/python3.8/site-packages

mkdir -p ./Logs

# NCPUS per task
NCPUS=1

SCRIPT=./htseq-count.sh
INPUTS=./Inputs/htseq-count.inputs

#########################################################
# Do not edit below this line
#########################################################

M=$(( PBS_NCI_NCPUS_PER_NODE / NCPUS )) #tasks per node

sed "s|^|${SCRIPT} |" ${INPUTS} > ${PBS_JOBFS}/input-file

mpirun --np $((M * PBS_NCPUS / PBS_NCI_NCPUS_PER_NODE)) \
        --map-by node:PE=${NCPUS} \
        nci-parallel \
        --verbose \
        --input-file ${PBS_JOBFS}/input-file
