#! /bin/bash

set -e

#########################################################
#
# Platform: NCI Gadi HPC
# Description: Creates input file for htseq-count_run_parallel.pbs
# for all samples in <cohort>.config
# Usage:
# sh htseq-count_make_inputs.sh <cohort>
# Author: Tracy Chew
# tracy.chew@sydney.edu.au
# Date last modified: 27/08/2020
#
# If you use this script towards a publication, please acknowledge the
# Sydney Informatics Hub (or co-authorship, where appropriate).
#
# Suggested acknowledgement:
# The authors acknowledge the scientific and technical assistance
# <or e.g. bioinformatics assistance of <PERSON>> of Sydney Informatics
# Hub and resources and services from the National Computational
# Infrastructure (NCI), which is supported by the Australian Government
# with access facilitated by the University of Sydney.
#
########################################################

#PBS -P <project>
#PBS -N htseq-count_matrix
#PBS -l walltime=05:00:00,ncpus=1,mem=32GB,wd
#PBS -q express
#PBS -W umask=022
#PBS -l storage=scratch/<project>
#PBS -o ./Logs/htseq-count_matrix.o
#PBS -e ./Logs/htseq-count_matrix.e

# PROVIDE PATH TO YOUR CONFIG FILE
config=../Sample_configs/cohort.config

mkdir -p ./Logs
perl ./htseq-count_make_matrix_custom.pl $config
