#!/bin/bash

set -e

#########################################################
#
# Platform: NCI Gadi HPC
#
# Author: Tracy Chew
# tracy.chew@sydney.edu.au
#
# If you use this script towards a publication, please acknowledge the
# Sydney Informatics Hub (or co-authorship, where appropriate).
#
# Suggested acknowledgement:
# The authors acknowledge the scientific and technical assistance
# <or e.g. bioinformatics assistance of <PERSON>> of Sydney Informatics
# Hub and resources and services from the National Computational
# Infrastructure (NCI), which is supported by the Australian Government
# with access facilitated by the University of Sydney.
#
#########################################################

# NOTE: no separate make_inputs.sh script - inputs are 
# created here. Please check this is done correctly 
# for your job
# For ~200 unmapped files, use
# #PBS -l walltime=02:00:00,ncpus=28,mem=128GB,wd
# #PBS -q normalbw

#PBS -P <project>
#PBS -N pigz
#PBS -l walltime=02:00:00,ncpus=28,mem=128GB,wd
#PBS -q normalbw
#PBS -W umask=022
#PBS -l storage=scratch/<project>
#PBS -o ./Logs/pigz.o
#PBS -e ./Logs/pigz.e

module load openmpi/4.0.2
module load nci-parallel/1.0.0a

mkdir -p ./Logs
NCPUS=1
INPUTS=./Inputs/pigz.inputs
SCRIPT=./pigz.sh

# CREATE INPUTS - CHANGE AS REQUIRED
# 1 file per line
# Paths must be relative to Scripts directory

ls -1 ../path/to/STAR/*Unmapped.out.mate* > ${INPUTS}
#find .. -name "*Unmapped.out.mate1" > ${INPUTS}
#find .. -name "*Unmapped.out.mate2" >> ${INPUTS}


#########################################################
# Do not edit below this line
#########################################################

M=$(( PBS_NCI_NCPUS_PER_NODE / NCPUS )) #tasks per node

sed "s|^|${SCRIPT} |" ${INPUTS} > ${PBS_JOBFS}/input-file

mpirun --np $((M * PBS_NCPUS / PBS_NCI_NCPUS_PER_NODE)) \
        --map-by node:PE=${NCPUS} \
        nci-parallel \
        --verbose \
        --input-file ${PBS_JOBFS}/input-file
